# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sscustom"
BBFILE_PATTERN_meta-sscustom = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sscustom = "10"

LAYERDEPENDS_meta-sscustom = "core"
LAYERSERIES_COMPAT_meta-sscustom = "kirkstone"
